### ISSUE TITLE
display info boxes when marker is clicked on map

### ISSUE THREAD

**Issue by cqliu1** [cqliu1/lets-hang#11]
use "snazzy-info-window" plugin

**Comment by cqliu1** [comment]
https://plainjs.com/javascript/plugins/snazzy-info-window-131/

**Comment by neophoenix733** [comment]
Hey Catherine! I am back on slack if you wanna chat. How is work n life?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
